### ISSUE TITLE
BigDecimal 计算double 类型数据精度问题

### ISSUE THREAD

**Issue by drinkagain** [LJWLgl/CommonUtil#1]
BigDecimal 计算double 类型数据，不能直接 new BigDecimal(double)；下面代码执行一下试试看

    public static void main(String[] args) {
        double a = 19.9;
        double b = 0.9;
        BigDecimal a1 = new BigDecimal(a);
        BigDecimal b1 = new BigDecimal(b);
        System.out.println(a1.add(b1).doubleValue());

        BigDecimal a2 = BigDecimal.valueOf(a);
        BigDecimal b2 = BigDecimal.valueOf(b);
        System.out.println(a2.add(b2).doubleValue());
    }

**Comment by LJWLgl** [comment]
Hi，new BigDecimal(double val)构造方法，确实有精度丢失的问题，可以通过new BigDecimal(String val)或者BigDecimal.valueof()来解决，后面我会修改，感谢你的issue

**Comment by LJWLgl** [comment]
记录一下网友给的解释：https://www.cnblogs.com/dzhou/p/9541910.html
